spring:
  application:
    name: ticket

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: postgres
    password: 4321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080